
name: Build Quarkus Project

on:
  push:
    branches:
      - dev
      - homolog
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: tarefas_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dar permissão ao Maven wrapper
        run: chmod +x mvnw

      - name: Build com perfil TEST (dev ou homolog)
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/homolog'
        run: ./mvnw clean install -Dquarkus.profile=test

      - name: Build com perfil PROD (main)
        if: github.ref == 'refs/heads/main'
        run: ./mvnw clean install -Dquarkus.profile=prod
